In [52]:
import numpy as np

In [53]:
bank_data = np.array([
    [1001, 12500, 720, 35, 5],
    [1002, 5400, 650, 20, 3],
    [1003, 9800, 700, 28, 4],
    [1004, 15000, 780, 40, 8],
    [1005, 3200, 600, 15, 2],
    [1006, 8700, 690, 25, 4],
    [1007, 4500, 640, 18, 3],
    [1008, 20000, 820, 50, 10],
    [1009, 7600, 710, 30, 6],
    [1010, 6100, 670, 22, 3]
])

In [54]:
#Q1.1: Create a 4x4 identity matrix using np.eye()
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [55]:
#Q1.2: Create an array of 8 zeros using np.zeros()
identity_matrix = np.zeros(8)
print(identity_matrix)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [56]:
#Q1.3: Create an array of 6 ones using np.ones()
identity_matrix = np.ones(6)
print(identity_matrix)


[1. 1. 1. 1. 1. 1.]


In [57]:
#Q1.4: Create an array with values from 0 to 15 using np.arange()
array_0_to_15 = np.arange(16)
print(array_0_to_15)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [58]:
#Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
evenly_spaced_array = np.linspace(0,100,8)
print(evenly_spaced_array)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


Question 2: Array Attributes and Information

In [126]:
#Q2.1: What is the shape of the banking_data array?
shape_of_bank_data = bank_data.shape
print(f"shape of the bank data:{shape_of_bank_data}")

shape of the bank data:(10, 5)


In [ ]:
#Q2.2: What is the data type of the banking_data array?
data_type_of_bank_data = bank_data.dtype
print(f"type of the bank data:{data_type_of_bank_data}")

type of the bank data:int64


In [ ]:
#Q2.3: What is the size (total number of elements) of the banking_data array?
size_of_bank_data =bank_data.size
print(f"size of the bank data:{size_of_bank_data}")

size of the bank data:50


In [ ]:
#Q2.4: What is the number of dimensions of the banking_data array?
num_of_dimensions = bank_data.ndim
print(f"number of dimensions of the bank data:{num_of_dimensions}")

number of dimensions of the bank data:2


In [ ]:
#Q2.5: What is the memory size of the banking_data array in bytes?
memory_size_of_bank_data = bank_data.nbytes
print(f"memory size of the bank data in bytes:{memory_size_of_bank_data}")

memory size of the bank data in bytes:400


In [ ]:
Question 3: Indexing and Slicing

In [ ]:
#Q3.1: Extract the first row of banking_data
first_row = bank_data[0]
print(f"first_row:{first_row}")


first_row:[ 1001 12500   720    35     5]


In [ ]:
#Q3.2: Extract the last row of banking_data
last_row = bank_data[-1]
print(f"last_row:{last_row}")

last_row:[1010 6100  670   22    3]


In [ ]:
#Q3.3: Extract the Account_Balance column (column index 1)
account_balance_column = bank_data[:,1]
print(f"account_balance_column:{account_balance_column}")

account_balance_column:[12500  5400  9800 15000  3200  8700  4500 20000  7600  6100]


In [ ]:
#Q3.4: Extract the first 4 rows and first 3 columns
subset_data = bank_data[:4,:3]
print(f"subset_data:{subset_data}")

subset_data:[[ 1001 12500   720]
 [ 1002  5400   650]
 [ 1003  9800   700]
 [ 1004 15000   780]]


In [ ]:
#Q3.5: Extract rows 3 to 7 (inclusive)
rows_3_to_7 = bank_data[3:8]
print(f"rows_3_to_7:{rows_3_to_7}")

rows_3_to_7:[[ 1004 15000   780    40     8]
 [ 1005  3200   600    15     2]
 [ 1006  8700   690    25     4]
 [ 1007  4500   640    18     3]
 [ 1008 20000   820    50    10]]


In [ ]:
Question 4: Mathematical Operations

In [ ]:
#Q4.1: Calculate the sum of all account balances
sum_of_account_balances = np.sum(bank_data[:,1])
print(f"sum of all account balances:{sum_of_account_balances}")

sum of all account balances:92800


In [ ]:
#Q4.2: Calculate the mean account balance
mean_of_account_balances = np.mean(bank_data[:,1])
print(f"mean of all account balances:{mean_of_account_balances}")

mean of all account balances:9280.0


In [ ]:
#Q4.3: Calculate the standard deviation of account balances
std_of_account_balances = np.std(bank_data[:,1])
print(f"std of all account balances:{std_of_account_balances}")

std of all account balances:4964.030620372924


In [ ]:
#Q4.4: Calculate the variance of account balances
varience_of_account_balances = np.var(bank_data[:,1])
print(f"varience of all account balances:{varience_of_account_balances}")

varience of all account balances:24641600.0


In [ ]:
#Q4.5: Calculate the median account balance
median_of_account_balances = np.median(bank_data[:,1])
print(f"median of all account balances:{median_of_account_balances}")

median of all account balances:8150.0


In [ ]:
Question 5: Statistical Functions

In [ ]:
#Q5.1: Find the minimum and maximum account balances
min_account_balance = np.min(bank_data[:,1])
max_account_balance = np.max(bank_data[:,1])
print(f"minimum account balance:{min_account_balance}")
print(f"maximum account balance:{max_account_balance}")

minimum account balance:3200
maximum account balance:20000


In [ ]:
#Q5.2: Find the minimum and maximum credit scores
min_credit_score = np.min(bank_data[:,2])
max_credit_score = np.max(bank_data[:,2])
print(f"minimum credit score:{min_credit_score}")
print(f"maximum credit score:{max_credit_score}")

minimum credit score:600
maximum credit score:820


In [ ]:
#Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
percentiles = np.percentile(bank_data[:,1],[25,50,75])
print(f"25th percentile of account balances:{percentiles[0]}")
print(f"50th percentile of account balances:{percentiles[1]}")
print(f"75th percentile of account balances:{percentiles[2]}")

25th percentile of account balances:5575.0
50th percentile of account balances:8150.0
75th percentile of account balances:11825.0


In [ ]:
#Q5.4: Calculate the correlation between account balance and credit score
correlation = np.corrcoef(bank_data[:,1],bank_data[:,2])
print(f"correlation between account balance and credit score:{correlation[0,1]}")

correlation between account balance and credit score:0.9697853713263144


In [ ]:
#Q5.5: Calculate the covariance between account balance and credit score
covariance = np.cov(bank_data[:,1],bank_data[:,2])
print(f"covariance between account balance and credit score:{covariance[0,1]}")

covariance between account balance and credit score:331288.8888888889


In [ ]:
Question 6: Array Reshaping and Manipulation

In [ ]:
#Q6.1: Reshape the banking_data to 5 rows × 10 columns
reshaped_bank_data = bank_data.reshape(5,10)
print(f"reshaped_bank_data:\n{reshaped_bank_data}")

reshaped_bank_data:
[[ 1001 12500   720    35     5  1002  5400   650    20     3]
 [ 1003  9800   700    28     4  1004 15000   780    40     8]
 [ 1005  3200   600    15     2  1006  8700   690    25     4]
 [ 1007  4500   640    18     3  1008 20000   820    50    10]
 [ 1009  7600   710    30     6  1010  6100   670    22     3]]


In [ ]:
#Q6.2: Flatten the banking_data to a 1D array
flattened_bank_data = bank_data.flatten()
print(f"flattend bank data:\n{flattened_bank_data}")

flattend bank data:
[ 1001 12500   720    35     5  1002  5400   650    20     3  1003  9800
   700    28     4  1004 15000   780    40     8  1005  3200   600    15
     2  1006  8700   690    25     4  1007  4500   640    18     3  1008
 20000   820    50    10  1009  7600   710    30     6  1010  6100   670
    22     3]


In [ ]:
#Q6.3: Transpose the banking_data
transposed_bank_data = bank_data.T
print(f"transposed bank data:\n{transposed_bank_data}")

transposed bank data:
[[ 1001  1002  1003  1004  1005  1006  1007  1008  1009  1010]
 [12500  5400  9800 15000  3200  8700  4500 20000  7600  6100]
 [  720   650   700   780   600   690   640   820   710   670]
 [   35    20    28    40    15    25    18    50    30    22]
 [    5     3     4     8     2     4     3    10     6     3]]


In [ ]:
#Q6.4: Split the banking_data into 2 equal parts vertically
split_bank_data = np.split(bank_data,2)
print(f"split bank data:\n{split_bank_data[0]}\n\n{split_bank_data[1]}")

split bank data:
[[ 1001 12500   720    35     5]
 [ 1002  5400   650    20     3]
 [ 1003  9800   700    28     4]
 [ 1004 15000   780    40     8]
 [ 1005  3200   600    15     2]]

[[ 1006  8700   690    25     4]
 [ 1007  4500   640    18     3]
 [ 1008 20000   820    50    10]
 [ 1009  7600   710    30     6]
 [ 1010  6100   670    22     3]]


In [ ]:
#Q6.5: Split the banking_data into 2 equal parts horizontally
split_bank_data_horizontal = np.hsplit(bank_data,[2])
print(f"split bank data horizontally:\n{split_bank_data_horizontal[0]}\n\n{split_bank_data_horizontal[1]}")

split bank data horizontally:
[[ 1001 12500]
 [ 1002  5400]
 [ 1003  9800]
 [ 1004 15000]
 [ 1005  3200]
 [ 1006  8700]
 [ 1007  4500]
 [ 1008 20000]
 [ 1009  7600]
 [ 1010  6100]]

[[720  35   5]
 [650  20   3]
 [700  28   4]
 [780  40   8]
 [600  15   2]
 [690  25   4]
 [640  18   3]
 [820  50  10]
 [710  30   6]
 [670  22   3]]


In [ ]:
Question 7: Logical Operations and Filtering

In [ ]:
#Q7.1: Find customers with account balance greater than $100,000
high_balance_customers = bank_data[bank_data[:,1]>100000]
print(f"customers with account balance greater than $100,000:\n{high_balance_customers}")

customers with account balance greater than $100,000:
[]


In [60]:
#Q7.2: Find customers with credit score greater than 800
high_credit_score_cust = bank_data[bank_data[:,2]>800]
print(f"customers with credit score greater than 800:\n{high_credit_score_cust}")

customers with credit score greater than 800:
[[ 1008 20000   820    50    10]]


In [62]:
#Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
filtered_customers = bank_data[(bank_data[:,4]>50) & (bank_data[:,2]<750)]
print(f"customers with transaction count greater than 50 AND credit score less than 750:\n{filtered_customers}")

customers with transaction count greater than 50 AND credit score less than 750:
[]


In [64]:
#Q7.4: Count how many customers have account balance between $10,000 and $100,000
count_customers_in_range = np.sum((bank_data[:,1]>10000) & (bank_data[:,1]<100000))
print(f"number of customers with account balance between $10,000 and $100,000:{count_customers_in_range}")

number of customers with account balance between $10,000 and $100,000:3


In [65]:
#Q7.5: Find the index of the customer with the highest credit score
index_of_highest_credit_score = np.argmax(bank_data[:,2])
print(f"index of the customer with the highest credit score:{index_of_highest_credit_score}")

index of the customer with the highest credit score:7


In [ ]:
Question 8: Sorting and Searching

In [66]:
#Q8.1: Sort the banking_data by account balance (ascending)
sorted_by_account_balance = bank_data[bank_data[:,1].argsort()]
print(f"banking data sorted by account balance (ascending):\n{sorted_by_account_balance}")

banking data sorted by account balance (ascending):
[[ 1005  3200   600    15     2]
 [ 1007  4500   640    18     3]
 [ 1002  5400   650    20     3]
 [ 1010  6100   670    22     3]
 [ 1009  7600   710    30     6]
 [ 1006  8700   690    25     4]
 [ 1003  9800   700    28     4]
 [ 1001 12500   720    35     5]
 [ 1004 15000   780    40     8]
 [ 1008 20000   820    50    10]]


In [67]:
#Q8.2: Sort the banking_data by credit score (descending)
sorted_by_credit_score = bank_data[bank_data[:,2].argsort()[::-1]]
print(f"banking data sorted by credit score (descending):\n{sorted_by_credit_score}")       

banking data sorted by credit score (descending):
[[ 1008 20000   820    50    10]
 [ 1004 15000   780    40     8]
 [ 1001 12500   720    35     5]
 [ 1009  7600   710    30     6]
 [ 1003  9800   700    28     4]
 [ 1006  8700   690    25     4]
 [ 1010  6100   670    22     3]
 [ 1002  5400   650    20     3]
 [ 1007  4500   640    18     3]
 [ 1005  3200   600    15     2]]


In [68]:
#Q8.3: Find the indices that would sort the array by years active
indices_sorted_by_years_active = bank_data[:,3].argsort()
print(f"indices that would sort the array by years active:{indices_sorted_by_years_active}")

indices that would sort the array by years active:[4 6 1 9 5 2 8 0 3 7]


In [69]:
#8.4: Find the customer with the second highest account balance
second_highest_account_balance_index = np.argsort(bank_data[:,1])[::-1][1]
print(f"index of the customer with the second highest account balance:{second_highest_account_balance_index}")  

index of the customer with the second highest account balance:3


In [70]:
#Q8.5: Find the customer with the lowest transaction count
lowest_transaction_count_index = np.argmin(bank_data[:,4])
print(f"index of the customer with the lowest transaction count:{lowest_transaction_count_index}")      

index of the customer with the lowest transaction count:4


In [ ]:
Question 9: Mathematical Functions

In [71]:
#Q9.1: Calculate the absolute values of all elements
absolute_values = np.abs(bank_data)
print(f"absolute values of all elements:\n{absolute_values}")

absolute values of all elements:
[[ 1001 12500   720    35     5]
 [ 1002  5400   650    20     3]
 [ 1003  9800   700    28     4]
 [ 1004 15000   780    40     8]
 [ 1005  3200   600    15     2]
 [ 1006  8700   690    25     4]
 [ 1007  4500   640    18     3]
 [ 1008 20000   820    50    10]
 [ 1009  7600   710    30     6]
 [ 1010  6100   670    22     3]]


In [72]:
#Q9.2: Calculate the square root of all account balances
square_root_account_balances = np.sqrt(bank_data[:,1])
print(f"square root of all account balances:\n{square_root_account_balances}")

square root of all account balances:
[111.80339887  73.48469228  98.99494937 122.47448714  56.56854249
  93.27379053  67.08203932 141.42135624  87.17797887  78.10249676]


In [73]:
#Q9.3: Calculate the square of all credit scores
square_of_credit_scores = np.square(bank_data[:,2])
print(f"square of all credit scores:\n{square_of_credit_scores}")

square of all credit scores:
[518400 422500 490000 608400 360000 476100 409600 672400 504100 448900]


In [74]:
#Q9.4: Calculate the exponential of all transaction counts
exponential_of_transaction_counts = np.exp(bank_data[:,4])
print(f"exponential of all transaction counts:\n{exponential_of_transaction_counts}")

exponential of all transaction counts:
[1.48413159e+02 2.00855369e+01 5.45981500e+01 2.98095799e+03
 7.38905610e+00 5.45981500e+01 2.00855369e+01 2.20264658e+04
 4.03428793e+02 2.00855369e+01]


In [75]:
#Q9.5: Calculate the natural logarithm of all account balances
natural_log_account_balances = np.log(bank_data[:,1])
print(f"natural logarithm of all account balances:\n{natural_log_account_balances}")

natural logarithm of all account balances:
[9.43348392 8.59415423 9.19013766 9.61580548 8.07090609 9.0710783
 8.41183268 9.90348755 8.93590353 8.71604405]


In [ ]:
Question 10: Advanced Operations

In [76]:
#Q10.1: Calculate the cumulative sum of account balances
cumulative_sum_account_balances = np.cumsum(bank_data[:,1])
print(f"cumulative sum of account balances:\n{cumulative_sum_account_balances}")

cumulative sum of account balances:
[12500 17900 27700 42700 45900 54600 59100 79100 86700 92800]


In [77]:
#10.2: Calculate the cumulative product of transaction counts
cumulative_product_transaction_counts = np.cumprod(bank_data[:,4])
print(f"cumulative product of transaction counts:\n{cumulative_product_transaction_counts}")

cumulative product of transaction counts:
[      5      15      60     480     960    3840   11520  115200  691200
 2073600]


In [78]:
#Q10.3: Calculate the difference between consecutive account balances
difference_account_balances = np.diff(bank_data[:,1])
print(f"difference between consecutive account balances:\n{difference_account_balances}")   

difference between consecutive account balances:
[ -7100   4400   5200 -11800   5500  -4200  15500 -12400  -1500]


In [79]:
#Q10.4: Calculate the gradient of account balances

gradient_account_balances = np.gradient(bank_data[:,1])
print(f"gradient of account balances:\n{gradient_account_balances}")

gradient of account balances:
[-7100. -1350.  4800. -3300. -3150.   650.  5650.  1550. -6950. -1500.]


In [80]:
#Q10.5: Calculate the histogram of account balances with 5 bins

histogram_of_account_balances, bin_edges = np.histogram(bank_data[:,1], bins=5)
print(f"histogram of account balances with 5 bins:\n{histogram_of_account_balances}")
print(f"bin edges for the histogram:\n{bin_edges}")

histogram of account balances with 5 bins:
[4 3 1 1 1]
bin edges for the histogram:
[ 3200.  6560.  9920. 13280. 16640. 20000.]


In [ ]:
Question 11: Random Numbers and Simulation


In [83]:
#Q11.1: Generate 6 random integers between 1 and 1000
np.random.randint(1,1000,6)

array([948, 612, 542, 648, 741, 214], dtype=int32)

In [86]:
#Q11.2: Generate 6 random floats between 0 and 1
np.random.rand(6)

array([0.2619325 , 0.1394075 , 0.89839704, 0.25030158, 0.26166287,
       0.91214274])

In [87]:
#Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)

random_normal_numbers = np.random.normal(700,100,6)
print(f"6 random numbers from normal distribution (mean=700, std=100):\n{random_normal_numbers}")

6 random numbers from normal distribution (mean=700, std=100):
[690.20971635 693.77245484 882.28948853 682.28469884 864.20010597
 793.53234378]


In [88]:
#Q11.4: Shuffle the banking_data rows randomly

shuffled_bank_data = np.random.permutation(bank_data)
print(f"shuffled banking data:\n{shuffled_bank_data}")

shuffled banking data:
[[ 1007  4500   640    18     3]
 [ 1008 20000   820    50    10]
 [ 1010  6100   670    22     3]
 [ 1006  8700   690    25     4]
 [ 1009  7600   710    30     6]
 [ 1005  3200   600    15     2]
 [ 1003  9800   700    28     4]
 [ 1002  5400   650    20     3]
 [ 1001 12500   720    35     5]
 [ 1004 15000   780    40     8]]


In [89]:
#Q11.5: Set random seed to 123 and generate 4 random numbers

np.random.seed(123)
np.random.rand(4)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477])

In [ ]:
Question 12: Linear Algebra Operations


In [90]:
#Q12.1: Calculate the dot product of account balance and credit score columns
dot_product = np.dot(bank_data[:,1], bank_data[:,2])
print(f"Dot product of account balance and credit score columns: {dot_product}")    

Dot product of account balance and credit score columns: 67756000


In [94]:
#Q12.2: Calculate the cross product of first two rows
cross_product = np.cross((bank_data[0,1:4]),(bank_data[1,1:4]))
print(f"Cross product of first two rows: {cross_product}")

Cross product of first two rows: [  -8350  -61000 4237000]


In [95]:
#Q12.3: Calculate the norm (magnitude) of the account balance column
balance_norm = np.linalg.norm(bank_data[:,1])

print(f"Norm of account balance column: {balance_norm}")

Norm of account balance column: 33280.62499413134


In [97]:
#Q12.4: Create a 3x3 matrix and calculate its determinant

matrix_3x3 = np.array([[1,2,3],[0,1,4],[5,6,0]])
determinant = np.linalg.det(matrix_3x3) 
print(f"determinant of the 3x3 matrix: {determinant}")

determinant of the 3x3 matrix: 0.9999999999999964


In [98]:
#Q12.5: Calculate the inverse of the 3x3 matrix
inverse_matrix = np.linalg.inv(matrix_3x3)
print(f"inverse of the 3x3 matrix:\n{inverse_matrix}")

inverse of the 3x3 matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [ ]:
Question 13: String Operation

In [100]:
#Q13.1: Convert all customer IDs to strings

customer_ids_as_strings = bank_data[:,0].astype(str)
print(f"customer IDs as strings:\n{customer_ids_as_strings}")

customer IDs as strings:
['1001' '1002' '1003' '1004' '1005' '1006' '1007' '1008' '1009' '1010']


In [104]:
#Q13.2: Check if any customer ID contains '100'

customer_id_contains_100 = np.char.find(customer_ids_as_strings,'100') != -1
print(f"any customer ID contains '100': {np.any(customer_id_contains_100)}")

any customer ID contains '100': True


In [105]:
#Q13.3: Convert all customer IDs to uppercase (if they were strings)

customer_ids_uppercase = np.char.upper(customer_ids_as_strings)
print(f"customer IDs in uppercase:\n{customer_ids_uppercase}")

customer IDs in uppercase:
['1001' '1002' '1003' '1004' '1005' '1006' '1007' '1008' '1009' '1010']


In [106]:
#Q13.4: Count the length of each customer ID string

customer_id_lengths = np.char.str_len(customer_ids_as_strings)
print(f"length of each customer ID string:\n{customer_id_lengths}")

length of each customer ID string:
[4 4 4 4 4 4 4 4 4 4]


In [109]:
#Q13.5: Replace '100' with 'CUST' in customer IDs

customer_ids_replaced = np.char.replace(customer_ids_as_strings,'100','CUST')
print(f"customer ids with replacement:\n{customer_ids_replaced}")


customer ids with replacement:
['CUST1' 'CUST2' 'CUST3' 'CUST4' 'CUST5' 'CUST6' 'CUST7' 'CUST8' 'CUST9'
 '1010']


In [ ]:
Question 14: Date and Time Operations


In [110]:
#Q14.1: Convert years active to months

months_active = bank_data[:,3] * 12
print(f"years active converted to months:\n{months_active}")

years active converted to months:
[420 240 336 480 180 300 216 600 360 264]


In [111]:
#Q14.2: Calculate the average years active

average_years_active = np.mean(bank_data[:,3])
print(f"average years active: {average_years_active}")

average years active: 28.3


In [116]:
#Q14.3: Find customers who have been active for more than 5 years

active_more_than_5_years = bank_data[bank_data[:,4]>5]
print(f"customers who have been active for more than 5 years:\n{active_more_than_5_years}")

customers who have been active for more than 5 years:
[[ 1004 15000   780    40     8]
 [ 1008 20000   820    50    10]
 [ 1009  7600   710    30     6]]


In [117]:
#Q14.4: Calculate the total time all customers have been active (in years)

total_years_active = np.sum(bank_data[:,3])
print(f"total time all customers have been active (in years): {total_years_active}")

total time all customers have been active (in years): 283


In [118]:
#Q14.5: Find the customer with the shortest time active

shortest_time_active_index = np.argmin(bank_data[:,3])
print(f"index of the customer with the shortest time active: {shortest_time_active_index}")

index of the customer with the shortest time active: 4


In [ ]:
Question 15: Advanced Array Operations


In [119]:
#Q15.1: Apply a function to calculate 5% interest on all account balances

interest_on_balances = bank_data[:,1] * 0.05
print(f"5% interest on all account balances:\n{interest_on_balances}")

5% interest on all account balances:
[ 625.  270.  490.  750.  160.  435.  225. 1000.  380.  305.]


In [120]:
#Q15.2: Use np.where to categorize customers by balance ranges
balance_categories = np.where(bank_data[:,1]<5000,'Low', np.where(bank_data[:,1]<15000,'Medium','High'))
print(f"balance categories for customers:\n{balance_categories}")



balance categories for customers:
['Medium' 'Medium' 'Medium' 'High' 'Low' 'Medium' 'Low' 'High' 'Medium'
 'Medium']


In [123]:
# Q15.3: Use np.select to categorize customers by credit score ranges

conditions = [
    bank_data[:,2] < 650,
    (bank_data[:,2] >= 650) & (bank_data[:,2] <= 750),
    bank_data[:,2] > 750
]

choices = ["Poor", "Average", "Excellent"]

credit_score_category = np.select(conditions, choices, default="Unknown")

print(f"credit score categories:\n{credit_score_category}")

credit score categories:
['Average' 'Average' 'Average' 'Excellent' 'Poor' 'Average' 'Poor'
 'Excellent' 'Average' 'Average']


In [124]:
#Q15.4: Use np.piecewise to apply different interest rates based on balance

interest_rates = np.piecewise(bank_data[:,1], [bank_data[:,1] < 5000, (bank_data[:,1] >= 5000) & (bank_data[:,1] < 15000), bank_data[:,1] >= 15000], [0.01, 0.02, 0.03])        
print(f"interest rates based on balance:\n{interest_rates}")

interest rates based on balance:
[0 0 0 0 0 0 0 0 0 0]


In [125]:
#Q15.5: Use np.apply_along_axis to calculate the sum of each row

row_sums = np.apply_along_axis(np.sum, 1, bank_data)
print(f"sum of each row:\n{row_sums}")

sum of each row:
[14261  7075 11535 16832  4822 10425  6168 21888  9355  7805]
